name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone and bootstrap vcpkg
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure with CMake
        run: |
          cmake -S cmake-vcpkg -B build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: |
          ctest --output-on-failure --test-dir build
